### ISSUE TITLE
Minify_CSS_Compressor Class not found Error

### ISSUE THREAD

**Issue by anupalhub** [Highstrike/cakephp-compressor#3]
I am getting Fatal error
`Class 'Minify_CSS_Compressor' not found`
`\app\Vendor\minify-3.0.0\lib\Minify\CSS.php`

Is the helper compatible with minify-3.0.0 ?

What should i do?

**Comment by highstrike** [comment]
Might not be compatible with 3.0.0 (even though the class still exists there)
I've updated the composer file to require 2.3.1 instead. See if that works

**Comment by anupalhub** [comment]
With 2.3.1 its still giving that same error.

**Comment by highstrike** [comment]
Try the 2.2 branch, I think that was what I was using 2 years ago

**Comment by highstrike** [comment]
Please tell me if that works because I don't have the means to test it myself, I'm not running cakephp 2.x anymore 😋

**Comment by anupalhub** [comment]
Nope. Still error.

**Comment by highstrike** [comment]
U're probably not loading the composer autoloader then

> Assuming you have installed Minify in your-project/lib/vendor/mrclay open your Controller/AppController.php and include composer's autoload include(ROOT . DS . 'lib/vendor/autoload.php');

**Comment by anupalhub** [comment]
Can I please use it without Composer? Am manually installing.

**Comment by highstrike** [comment]
Well... composer makes sure those classes are loaded and available for use where they are needed.

I only use the function `minify` from 3 classes (as seen on these lines)
- https://github.com/highstrike/cakephp-compressor/blob/master/View/Helper/CompressorHelper.php#L228
- https://github.com/highstrike/cakephp-compressor/blob/master/View/Helper/CompressorHelper.php#L255
- https://github.com/highstrike/cakephp-compressor/blob/master/View/Helper/CompressorHelper.php#L288

That's why you get a fatal error with `Minify_CSS_Compressor`. It can't find the class loaded because you probably didn't include the file containing that class (which is here btw https://github.com/mrclay/minify/blob/3.x/lib/Minify/CSS/Compressor.php)

So if you don't want to use composer or composer's autoload file (that makes sure all the required classes are loaded) you will have to include the files manually, and go through each error till it works.

But like i said, if you just include the composer's autoload file then all of the classes will be available.

**Comment by anupalhub** [comment]
Am able to resolve errors with finally going with Composer install. 
But the combined CSS am getting is empty. Can you please suggest any solution?

**Comment by highstrike** [comment]
Do some debugging and see why they are empty, I wouldn't know what could be going on. Try with just one css file and then add them one by one and see where it fails.

**Comment by anupalhub** [comment]
I am trying it on CakePHP 2.5 version. Tried with single CSS file and still the cache CSS is empty. 
Didn't find any error!

**Comment by highstrike** [comment]
Read again the dependencies... Cake 2.6 and PHP 5.4.

**Comment by anupalhub** [comment]
Instead of 'css' folder i have my css files in different folder `/apps/global/css/` 
I think its not taking the CSS files relative path. I also tried to give absolute path but still empty files. 
My code is looking like
```
$this->Compressor->style(array(
            '/apps/global/css/components-rounded',
            '/apps/global/css/plugins',
            '/apps/account/layout/css/layout',
            '/apps/account/layout/css/leadxen',
            '/apps/account/layout/css/custom',
        ));
```

I guess am doing wrong with giving paths. However same works while using `Html->css` 
Can you please help?
Thanks

**Comment by highstrike** [comment]
The compressor is using `Configure::read('App.cssBaseUrl')` as prefix here -> https://github.com/highstrike/cakephp-compressor/blob/master/View/Helper/CompressorHelper.php#L83

depending on what that is in your `config/core.php` you might try without the prefix slash so just `apps/global...` or with a `../apps/global.....`

**Comment by anupalhub** [comment]
I now tired with moving some files in `css` folder at root and still showing empty compressed file. 
Can you please check this on your end if its working still?

**Comment by highstrike** [comment]
> Please tell me if that works because I don't have the means to test it myself, I'm not running cakephp 2.x anymore 😋 

I'm using cake 3.4 on all my projects now, so I can't check why it doesn't work for you.

If you upgrade to cake 3 you can use https://github.com/unimatrix/cakephp-utility
If you upgrade to cake 3.4 you can use https://github.com/unimatrix/cake
